import type { AIProvider, ContentPart, GenerateRequest, GenerateResponse, JsonSchema, KnowledgeHint } from "@/lib/ai/types";
import { textOf } from "@/lib/ai/types";
import { tokenize } from "@/lib/knowledge/embeddings";

/**
 * OFFLINE DEMO MODEL — not an AI model.
 *
 * A deterministic, rule-based stand-in used when no AI provider is configured
 * (and in automated tests). It lets owners exercise the whole platform — runtime,
 * permissions, approvals, workflows — without an API key. Its behaviour is
 * intentionally simple and every surface that shows its output labels it.
 *
 *  - Answers questions extractively from retrieved company knowledge (with sources).
 *  - Calls a tool only when the request clearly names it (keyword match).
 *  - Fills structured-output schemas with transparent heuristics.
 */

export const OFFLINE_NOTICE = "Offline demo model — rule-based output, not AI reasoning.";

function sentences(text: string): string[] {
  return text
    .replace(/\s+/g, " ")
    .split(/(?<=[.!?])\s+(?=[A-Z0-9"'(])/)
    .map((s) => s.trim())
    .filter((s) => s.length > 20);
}

function overlap(a: string[], b: Set<string>) {
  let n = 0;
  for (const t of a) if (b.has(t)) n++;
  return n;
}

function extractiveAnswer(question: string, knowledge: KnowledgeHint[]): string | null {
  const q = new Set(tokenize(question));
  if (q.size === 0 || knowledge.length === 0) return null;
  const scored = knowledge
    .flatMap((k) => sentences(k.content).map((s, idx) => ({ k, s, idx, score: overlap(tokenize(s), q) })))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);
  if (scored.length === 0) return null;
  const sources = [...new Set(scored.map((x) => `${x.k.source}${x.k.page ? `, page ${x.k.page}` : ""}`))];
  const body = scored.map((x) => `• ${x.s}`).join("\n");
  return `Here's what our approved knowledge says:\n\n${body}\n\nSource: ${sources.join("; ")}`;
}

const EMAIL_RE = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;

function heuristicScore(text: string): number {
  const t = text.toLowerCase();
  let score = 45;
  if (EMAIL_RE.test(text)) score += 10;
  if (/\b(company|inc|ltd|llc|gmbh|corp)\b|https?:\/\//.test(t)) score += 10;
  if (/\b(budget|enterprise|urgent|demo|pricing|quote|buy|purchase|annual)\b/.test(t)) score += 20;
  if (/\b(\d{2,}\s*(employees|seats|users))\b/.test(t)) score += 10;
  if (/\b(student|test|spam|unsubscribe)\b/.test(t)) score -= 25;
  return Math.max(0, Math.min(100, score));
}

function fillSchema(schema: JsonSchema, key: string, ctx: { text: string; score: number; agentName: string }): unknown {
  const type = schema.type as string | undefined;
  const k = key.toLowerCase();
  if (Array.isArray(schema.enum) && schema.enum.length) {
    const values = schema.enum as unknown[];
    const pick = (v: string) => values.find((x) => String(x).toLowerCase() === v);
    if (/qualif|category|tier|status|decision|action|outcome/.test(k)) {
      const bySc = ctx.score >= 80 ? pick("qualified") ?? pick("outreach") ?? pick("high") : ctx.score >= 50 ? pick("nurture") ?? pick("medium") : pick("archive") ?? pick("low") ?? pick("unqualified");
      if (bySc !== undefined) return bySc;
    }
    return values[0];
  }
  if (type === "object" || schema.properties) {
    const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
    return Object.fromEntries(Object.entries(props).map(([pk, ps]) => [pk, fillSchema(ps, pk, ctx)]));
  }
  if (type === "array") {
    const items = (schema.items ?? { type: "string" }) as JsonSchema;
    if ((items.type ?? "string") === "string") return [...new Set(tokenize(ctx.text))].slice(0, 5);
    return [];
  }
  if (type === "number" || type === "integer") {
    if (k.includes("score")) return ctx.score;
    if (k.includes("confidence")) return 0.5;
    return 0;
  }
  if (type === "boolean") return k.includes("approv") ? false : ctx.score >= 50;
  // string
  if (/reason|summary|explanation|rationale|notes?/.test(k)) return `Heuristic assessment by the offline demo model (not AI) based on the provided details. ${OFFLINE_NOTICE}`;
  if (/subject/.test(k)) return "Quick follow-up";
  if (/body|email|message|draft|content|text|reply|response/.test(k)) {
    const name = /name[:\s]+([A-Z][a-z]+)/.exec(ctx.text)?.[1];
    return `Hi${name ? ` ${name}` : ""},\n\nThanks for your interest. I'd love to learn more about what you're looking for and share how we can help. Would you be open to a short call this week?\n\nBest regards,\n${ctx.agentName}\n\n[Draft generated by the offline demo model — review before sending.]`;
  }
  return ctx.text.slice(0, 160) || "n/a";
}

function buildToolInput(schema: JsonSchema, text: string): Record<string, unknown> {
  const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
  const required = new Set((schema.required as string[] | undefined) ?? []);
  const out: Record<string, unknown> = {};
  const email = EMAIL_RE.exec(text)?.[0];
  const quoted = /"([^"]{2,})"|'([^']{2,})'/.exec(text);
  for (const [name, p] of Object.entries(props)) {
    const n = name.toLowerCase();
    const type = p.type as string | undefined;
    let value: unknown;
    if (n.includes("email") || n === "to") value = email;
    else if (/query|search|keyword|term|q$|name|company|topic/.test(n)) value = quoted?.[1] ?? quoted?.[2] ?? text.replace(/^(please\s+)?(can you\s+)?/i, "").slice(0, 120);
    else if (n.includes("subject")) value = "Following up";
    else if (/body|message|content/.test(n)) value = text;
    else if (type === "number" || type === "integer") value = Number(/\d+(\.\d+)?/.exec(text)?.[0] ?? 0);
    else if (Array.isArray(p.enum)) value = p.enum[0];
    if (value !== undefined && value !== "") out[name] = value;
    else if (required.has(name) && type === "string") out[name] = text.slice(0, 120);
  }
  return out;
}

export function createOfflineProvider(): AIProvider {
  return {
    kind: "OFFLINE",
    async generate(req: GenerateRequest): Promise<GenerateResponse> {
      const last = req.messages[req.messages.length - 1];
      const lastText = last ? textOf(last.content) : "";
      const hints = req.offlineHints ?? { knowledge: [], agentName: "The employee", taskText: lastText };
      const taskText = hints.taskText || lastText;
      const usage = { inputTokens: Math.ceil((req.system.length + JSON.stringify(req.messages).length) / 4), outputTokens: 0 };
      const done = (content: ContentPart[], stopReason: GenerateResponse["stopReason"] = "end"): GenerateResponse => {
        usage.outputTokens = Math.ceil(JSON.stringify(content).length / 4);
        return { content, stopReason, usage, model: "offline-demo", provider: "OFFLINE" };
      };
      const toolResults = last?.content.filter((p) => p.type === "tool_result") ?? [];
      const ctx = { text: taskText, score: heuristicScore(taskText), agentName: hints.agentName };

      // Structured output requested.
      if (req.responseSchema) {
        const obj = fillSchema(req.responseSchema.schema, req.responseSchema.name, ctx);
        return done([{ type: "text", text: JSON.stringify(obj) }]);
      }

      // Continuing after tool results: summarise them.
      if (toolResults.length > 0) {
        const lines = toolResults.map((r) => {
          if (r.type !== "tool_result") return "";
          if (r.isError) return `• ${r.name.replace(/__/g, ".")}: could not complete — ${r.content.slice(0, 300)}`;
          return `• ${r.name.replace(/__/g, ".")}: ${summarise(r.content)}`;
        });
        return done([{ type: "text", text: `Done. Results:\n${lines.join("\n")}` }]);
      }

      // A tool is clearly requested.
      const priorToolUse = req.messages.some((m) => m.content.some((p) => p.type === "tool_call"));
      if (!priorToolUse && req.tools?.length && lastText) {
        const words = new Set(tokenize(lastText));
        const ranked = req.tools
          .filter((t) => !t.name.startsWith("nby_"))
          .map((t) => ({ t, score: overlap(tokenize(`${t.name.replace(/[_-]+/g, " ")} ${t.description}`), words) }))
          .sort((a, b) => b.score - a.score);
        const best = ranked[0];
        if (best && best.score >= 2) {
          return done(
            [
              { type: "text", text: `I'll use ${best.t.name.replace(/__/g, ".")}.` },
              { type: "tool_call", id: `offline_${Date.now().toString(36)}`, name: best.t.name, input: buildToolInput(best.t.inputSchema, lastText) },
            ],
            "tool_use",
          );
        }
      }

      const answer = extractiveAnswer(lastText || taskText, hints.knowledge);
      if (answer) return done([{ type: "text", text: answer }]);
      return done([
        {
          type: "text",
          text:
            "I couldn't find approved company knowledge that answers this, so I won't guess. " +
            "I'm running on the offline demo model, which can only retrieve knowledge and follow simple rules — connect an AI provider in Settings → AI providers for full reasoning.",
        },
      ]);
    },
  };
}

function summarise(raw: string): string {
  // Tool output reaches the model wrapped as untrusted data; summarise the payload, not the wrapper.
  const content = raw.replace(/^\s*<untrusted_data[^>]*>\s*/, "").replace(/\s*<\/untrusted_data>\s*$/, "");
  try {
    const parsed = JSON.parse(content);
    if (Array.isArray(parsed)) return `${parsed.length} result(s)${parsed.length ? `: ${parsed.slice(0, 3).map(label).join(", ")}` : ""}`;
    if (parsed && typeof parsed === "object") {
      const o = parsed as Record<string, unknown>;
      if (Array.isArray(o.results)) return `${o.results.length} result(s)${o.results.length ? `: ${(o.results as unknown[]).slice(0, 3).map(label).join(", ")}` : ""}`;
      return Object.entries(o)
        .slice(0, 4)
        .map(([k, v]) => `${k}: ${typeof v === "object" ? JSON.stringify(v).slice(0, 60) : String(v)}`)
        .join("; ");
    }
  } catch {
    /* not JSON */
  }
  return content.slice(0, 200);
}

function label(item: unknown): string {
  if (item && typeof item === "object") {
    const o = item as Record<string, unknown>;
    return String(o.name ?? o.title ?? o.email ?? o.id ?? JSON.stringify(o).slice(0, 40));
  }
  return String(item);
}
